nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: ./bundles/@yarnpkg/plugin-unused-resolutions.js
    spec: bundles/@yarnpkg/plugin-unused-resolutions.js
  - checksum: 627893516485148067c93dbcad672faf71332596b318b10aabf48b7fbdb8d620fedaf1004b922dd08f77c7d0b688a9e6f722d604f2bd22b8196baf2d3d378566
    path: .yarn/plugins/plugin-dedupe-on-install.cjs
    spec: "https://raw.githubusercontent.com/ambar/yarn-plugin-dedupe-on-install/96ffd15fdb25310613f003a2c258dfd73eaa36a1/index.js"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
