nodeLinker: node-modules
nmHoistingLimits: workspaces

plugins:
  - path: ./bundles/@yarnpkg/plugin-unused-resolutions.js
    spec: bundles/@yarnpkg/plugin-unused-resolutions.js

yarnPath: .yarn/releases/yarn-4.9.1.cjs
